export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT"
export const FETCH_PRODUCT_ERROR= "FETCH_PRODUCT"

export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const FETCH_SUBCATEGORY = "FETCH_SUBCATEGORY"
export const FETCH_SUBCATEGORY1 = "FETCH_SUBCATEGORY1"
export const FETCH_SUBCATEGORY2 = "FETCH_SUBCATEGORY2"
export const ISLOGIN = "ISLOGIN"
export const FETCH_CART_PRODUCT = "FETCH_CART_PRODUCT"
export const FETCH_WISHLIST_PRODUCT = "FETCH_WISHLIST_PRODUCT"
export const GET_SUM_OF_CART = "GET_SUM_OF_CART"

